name: recepi

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo " start instslling docker compose"
          pip install docker-compose
          echo "Finish installation of docker compose"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - run: |
          python -m pip install --upgrade pip
          cd ..
          pip install -r requirements.txt
          docker-compose run app sh -c "python manage.py test && flake8"