name: recepi

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: installing docker
      - uses: actions/checkout@master
      - run: |
          echo " start instslling docker compose"
          pip install docker-compose
          echo "Finish installation of docker compose"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install requrements
        run: |
          echo "installing dependance"
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - uses: actions/checkou@master
      - name: Run Tests
        run: |
          docker-compose run app sh -c "python manage.py test && flake8