name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - run: pip install docker-compose
  job2:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6]
    steps:
      - uses: action/checkout@v2
      - name: Set up Pyhton %{{ matrx.python-version}}
        uses: action/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}
      - name: Install requrements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          docker-compose run app sh -c "python manage.py test && flake8