name: recepi

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo " start instslling docker compose"
          pip install docker-compose
          echo "Finish installation of docker compose"
  job2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.6
        uses: actions/setup-python@master
        with:
            python-version: 3.6
      - name: Install dependencise
        run: |
          pip3 install virtualenv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt

  job3:
    needs: [job1, job2]
    runs-on: ubuntu-latest
    steps:
      - run: |
          docker-compose run app sh -c "python manage.py test && flake8"