name: recepi

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: installing docker
        uses: actions/checkout@v2
        run: |
          echo " start instslling docker compose"
          pip install docker-compose
          echo "Finish installation of docker compose"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Install requrements
        uses: actions/checkout@master
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        uses: actions/checkout@master
        run: |
          docker-compose run app sh -c "python manage.py test && flake8"