name: recepe

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo " start instslling docker compose"
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          pip install docker-compose
          echo "Finish installation of docker compose"
          echo docker-compose --version
  job2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.6
        uses: actions/setup-python@master
        with:
            python-version: 3.6
      - name: create and start virtual enviroment
        run: |
          python3 -m venv venv
          source venv/bin/activate
      - name: Install dependance
        run: pip install -r requirements.txt
  job3:
    needs: [job1, job2]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: run test
        run: |
          docker-compose run app sh -c "python manage.py test && flake8"